### PR TITLE
Xcode: Use new XCTSkip to disable tests

### PR DESCRIPTION
**Pull request by jonreid**

### CODE REVIEW

**Comment by jonreid** [comment]
The test runner recognizes the test, but shows that it wasn't run. That doesn't really matter for the exercise, but this is "the new way" that folks should use in actual tests. So, trying to set an example with the code.

**Comment by jlangr** [comment]
Thanks Jon!

Paraphrasing: You want to deemphasize the old way (of prefixing the test function name with "DISABLED_," because it doesn't let you know that you have ignored tests when you run tests.

I can't think of a reason why it'd be a good thing for folks to not know that tests weren't getting run, so my question would be (for the test runner designers), why not just change the test runner to report the count of DISABLED_ tests?

**Comment by jonreid** [comment]
`DISABLED` was a hack, not a standard. The only requirement for a test is that the name starts with `test` and it has no arguments. So I've use `ZZZ` by myself, but starting using `DISABLED` on teams to document what was going on.

I really wish we had an `@Test` annotation and could drop the old-fashioned `test` name. I also wish we could use back-ticks and spaces in the name.

**Comment by jonreid** [comment]
But I work on Apple stuff 🤷🏻

**Comment by jlangr** [comment]
aha! :-)

thanks for the nuggets--much appreciated!

**Pull request merged**
